### ISSUE TITLE
bytes() on empty response body throws Exception

### ISSUE THREAD

**Issue by JanHolger** [JavaWebStack/HTTP-Client#2]
**Describe the Bug**

**Expected behavior**
Return empty byte array

**Screenshots / Logs**
```
Exception in thread "main" java.lang.NullPointerException
	at org.javawebstack.httpclient.HTTPRequest.readAll(HTTPRequest.java:261)
	at org.javawebstack.httpclient.HTTPRequest.execute(HTTPRequest.java:236)
	at org.javawebstack.httpclient.HTTPRequest.status(HTTPRequest.java:139)
```

**Environment Information:**
 - Java Language Level 8
 - Version 1.0.0

**Comment by JanHolger** [comment]
Fixed in f9c8f48396cb68d2728f1cb5fd3d4e63df6a9888
